from typing import Protocol, Any


class IObjectDetector(Protocol):
    def detect(self, image: Any, **kwargs) -> Any:...
    def load_model(self, model_path: str, **kwargs) -> Any:...
    def _preprocess(self, image: Any) -> Any:...
    def _postprocess(self, outputs: Any, **kwargs) -> Any:...

